all:
	# gcc -o tutorial01 tutorial01.c -lswscale -lavutil -lavformat -lavcodec  -lavutil -lm -lz -I/home/yzg/ffmpeg_build/include -L/usr/local/lib
	# gcc -o tutorial03 tutorial03.c -lswscale -lavutil -lavformat -lavcodec  -lavutil -lm -lz -I/home/yzg/ffmpeg_build/include -L/usr/local/lib  `sdl-config --cflags --libs`
	gcc -o aac_to_pcm aac_to_pcm.c -lswresample -lswscale -lavutil -lavformat -lavcodec  -lavutil -lm -lz -I/home/yzg/ffmpeg_build/include -L/usr/local/lib
